name: test-env
dependencies:
  - conda-build  # for conda index
  - pip
  - coverage
  - coveralls
  - doctest
  - pytest
  - pytest-cov
  - pytest-timeout
  - pytest-xvfb
  - numpy
  - matplotlib==3.6.3   # 3.7.0 breaks, can be removed when fixed
  - scipy
