name: test-env
dependencies:
  - conda-build  # for conda index
  - pip
  - coverage
  - coveralls
  - doctest
  - pytest
  - pytest-cov
  - pytest-timeout
  - pytest-xvfb
  - numpy
  - matplotlib
  - scipy
